import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {integratePersonality,integratePersonalityClient} from '../../extensions/personality/integrate.mjs';
import {integrateMemory,installMemoryRuntime} from '../../extensions/memory/integrate.mjs';
import {integrateProactive} from '../../extensions/proactive/integrate.mjs';
const windows=fileURLToPath(new URL('../',import.meta.url)),root=path.dirname(windows.slice(0,-1));
const work=path.join(windows,'.build','work');
const manifest=JSON.parse(await fs.readFile(path.join(windows,'upstream.json'),'utf8'));
export async function verify(){for(const [file,hash] of Object.entries(manifest.files)){
 const data=await fs.readFile(path.join(root,file),'utf8');
 if(createHash('sha256').update(data.replaceAll('\r\n','\n')).digest('hex')!==hash)throw Error('Upstream file changed: '+file+'. Review/rebase the Windows patches before building.');
}}
await verify();
if(path.dirname(work)!==path.join(windows,'.build')||path.basename(work)!=='work')throw Error('Unsafe build path');
await fs.rm(work,{recursive:true,force:true});await fs.mkdir(work,{recursive:true});
for(const file of ['src','test','package.json','tsconfig.json','cordis.patch.yml','README.md','README.zh.md','wechat-clawbot-INSTALL.md','LICENSE','NOTICE'])await fs.cp(path.join(root,file),path.join(work,file),{recursive:true});
async function patch(file,from,to){const p=path.join(work,file);const content=(await fs.readFile(p,'utf8')).replaceAll('\r\n','\n');if(content.split(from).length!==2)throw Error('Patch anchor drift: '+file+' / '+from.slice(0,60));await fs.writeFile(p,content.replace(from,to));}
// Only the generated copy is changed; each anchor must match exactly once.
await patch('src/codex-rpc.ts','import { spawn, type ChildProcessWithoutNullStreams }','import { type ChildProcessWithoutNullStreams }');
await patch('src/codex-rpc.ts','import WebSocket from "ws";','import WebSocket from "ws";\nimport {spawnTool as spawn,findTool,validateSocket,closeChild} from "./windows-platform.js";');
const rpc=await fs.readFile(path.join(work,'src/codex-rpc.ts'),'utf8');
const start=rpc.indexOf('export function findCodexBinary('),end=rpc.indexOf('\nexport class CodexAppServer',start);
if(start<0||end<0)throw Error('Codex discovery boundary changed');
await fs.writeFile(path.join(work,'src/codex-rpc.ts'),rpc.slice(0,start)+'export function findCodexBinary(override?:string):string { return findTool("codex",override); }\n'+rpc.slice(end));
await patch('src/codex-rpc.ts','    if (!path.isAbsolute(socketPath)) {\n      return Promise.reject(new Error("codexSocket must be an absolute IPC path"));\n    }','    try { validateSocket(socketPath); } catch(error) { return Promise.reject(error); }');
await patch('src/codex-rpc.ts','    child?.kill();','    closeChild(child);');
await patch('src/codex-peer.ts','import path from "node:path";','import path from "node:path";\nimport {defaultSocket} from "./windows-platform.js";');
await patch('src/codex-peer.ts','path.join(process.env.CODEX_HOME || path.join(os.homedir(), ".codex"), "app-server-control", "app-server-control.sock")','defaultSocket()');
await patch('src/config.ts','  codexTransport: "socket",','  codexTransport: "stdio",');
await patch('src/config.ts','codexTransport: r.codexTransport === "stdio" ? "stdio" : "socket",','codexTransport: r.codexTransport === "socket" ? "socket" : "stdio",');
await patch('src/config.ts','    .default("socket")','    .default("stdio")');
await patch('src/claude-peer.ts','import { execFile } from "node:child_process";','import {execTool as execFile,findTool} from "./windows-platform.js";');
const claude=await fs.readFile(path.join(work,'src/claude-peer.ts'),'utf8'),a=claude.indexOf('function findClaude():'),b=claude.indexOf('\n/** Cap on transcript',a);
if(a<0||b<0)throw Error('Claude discovery boundary changed');
await fs.writeFile(path.join(work,'src/claude-peer.ts'),claude.slice(0,a)+'function findClaude():string|undefined { const bin=findTool("claude");return fs.existsSync(bin)?bin:undefined; }\n'+claude.slice(b));
await fs.copyFile(path.join(windows,'adapters/platform.ts'),path.join(work,'src/windows-platform.ts'));
await fs.copyFile(path.join(windows,'adapters/image-compress.ts'),path.join(work,'src/image-compress.ts'));
await patch('src/client.js','  id: "wechat-clawbot",','  id: "wechat-clawbot-windows",');
await patch('src/client.js','    const PACKAGE = "wechat-clawbot";','    const PACKAGE = "wechat-clawbot-windows";');
await integratePersonality(work,patch);
await integrateMemory(work,patch);
await integrateProactive(work,patch);
const tsc=spawnSync(process.execPath,[path.join(windows,'node_modules/typescript/bin/tsc'),'-p',path.join(work,'tsconfig.json')],{cwd:work,stdio:'inherit',windowsHide:true});
if(tsc.status!==0)throw Error('TypeScript build failed');
await integratePersonalityClient(work,patch);
await fs.copyFile(path.join(work,'src/client.js'),path.join(work,'lib/client.js'));
await fs.copyFile(path.join(windows,'adapters/image-worker.mjs'),path.join(work,'lib/windows-image-worker.mjs'));
await installMemoryRuntime(work);
await patch('cordis.patch.yml',"name: 'wechat-clawbot'","name: 'wechat-clawbot-windows'");
const pkg=JSON.parse(await fs.readFile(path.join(work,'package.json'),'utf8'));
pkg.name='wechat-clawbot-windows';pkg.version=JSON.parse(await fs.readFile(path.join(windows,'package.json'),'utf8')).version;pkg.description+=' Windows adaptation, personality, chatbot-scoped MemOS, and randomized sharing.';pkg.dependencies.sharp='0.35.5';delete pkg.devDependencies;delete pkg.scripts;
Object.assign(pkg.dependencies,{'@huggingface/transformers':'4.3.1','@preact/signals':'2.9.0','@sinclair/typebox':'0.34.48','better-sqlite3':'12.10.0','preact':'10.29.1','uuid':'14.0.2','yaml':'2.8.3'});
pkg.peerDependencies['@deepseek-ai/dsh-timeout']='^0.2.0-rc.2';
pkg.repository={type:'git',url:'git+https://github.com/genius-FXC/wechat-clawbot-for-Windows.git'};pkg.files.push('WINDOWS.md','PERSONALITY.md','MEMOS-REVIEW.md','PROACTIVE.md');
pkg.homepage='https://github.com/genius-FXC/wechat-clawbot-for-Windows/tree/windows-adaptation/windows';
pkg.bugs={url:'https://github.com/genius-FXC/wechat-clawbot-for-Windows/issues'};
pkg.types='lib/index.d.ts';pkg.exports['.'].types='./lib/index.d.ts';pkg.exports['./cli'].types='./lib/cli.d.ts';
await fs.writeFile(path.join(work,'package.json'),JSON.stringify(pkg,null,2)+'\n');
await fs.writeFile(path.join(work,'WINDOWS.md'),(await fs.readFile(path.join(windows,'README.md'),'utf8')).replaceAll('../extensions/personality/README.md','PERSONALITY.md').replaceAll('../extensions/memory/REVIEW.md','MEMOS-REVIEW.md').replaceAll('../extensions/proactive/README.md','PROACTIVE.md'));
await fs.copyFile(path.join(root,'extensions/personality/README.md'),path.join(work,'PERSONALITY.md'));
await fs.copyFile(path.join(root,'extensions/memory/REVIEW.md'),path.join(work,'MEMOS-REVIEW.md'));
await fs.copyFile(path.join(root,'extensions/proactive/README.md'),path.join(work,'PROACTIVE.md'));
await verify();console.log('Windows runtime built. All '+Object.keys(manifest.files).length+' upstream files unchanged.');
